projeto/core/urls.py
from django.urls import path
from projeto.core import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('list_vendas', views.list_vendas, name='list_vendas'),
    path('financas/', views.financas, name='financas'),
    path('vendas-usuario-detalhes/<str:nome>/', views.vendas_usuario_detalhes, name='vendas_usuario_detalhes'),
]

projeto/estoque/urls.py
from django.urls import path
from projeto.estoque import views 

app_name = 'estoque'

urlpatterns = [
    path('', views.estoque_entrada_list, name='estoque_entrada_list'),
    path('saida/', views.estoque_saida_list, name='estoque_saida_list'),
    path('add/', views.estoque_entrada_add, name='estoque_entrada_add'),  
    path('saida/add/', views.estoque_saida_add, name='estoque_saida_add'),  
    path('entrada/<int:pk>/', views.estoque_entrada_detail, name='estoque_entrada_detail'),
    path('saida/<int:pk>/', views.estoque_saida_detail, name='estoque_saida_detail'),
    path('estoque/baixa/', views.dar_baixa_estoque_add, name='dar_baixa_estoque_add'),
    path('estoque/baixa/saida', views.dar_baixa_estoque_saida, name='dar_baixa_estoque_saida'),
]

projeto/produto/urls.py
from django.urls import path
from projeto.produto import views

app_name = 'produto'

urlpatterns = [
    path('', views.produto_list, name='produto_list'),
    path('<int:pk>/', views.produto_detail, name='produto_detail'),
    path('add/', views.ProdutoCreate.as_view(), name='produto_add'),
    path('<int:pk>/edit/', views.ProdutoUpdate.as_view(), name='produto_edit'),
    path('<int:pk>/deletar/', views.produto_delete, name='produto_delete'),
    path('<int:pk>/json/', views.produto_json, name='produto_json'),
]

projeto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('', include('projeto.core.urls')),
    path('produto/', include('projeto.produto.urls')),
    path('estoque/', include('projeto.estoque.urls')),
    path('vendas/', include('projeto.vendas.urls')),
    path('fornecedores/', include('projeto.fornecedores.urls')),
    path('admin/', admin.site.urls),
    path('user/', include('projeto.user.urls')),
    path('ingrediente/', include('projeto.ingrediente.urls')),
]

projeto/user/urls.py
from django.urls import path 
from projeto.user import views

app_name = 'user'

urlpatterns = [
    path('dashboard/', views.user_dashboard, name='user_dashboard'),
    path('signup/', views.signup, name='signup'),
    path('signin/', views.signin, name='signin'),
    path('logout/', views.logout, name='logout'),
]

projeto/vendas/urls.py
from django.urls import path
from projeto.vendas import views

app_name = 'vendas'

urlpatterns = [
    path('register_venda/', views.register_venda, name='register_venda'),
    path('gerar_recibo/<int:venda_id>/', views.gerar_recibo, name='gerar_recibo'), 
]

projeto/core/models.py
from django.db import models

# Create your models here.
class TimeStampedModel(models.Model):
    created = models.DateTimeField(
        'criado em',
        auto_now_add= True,
        auto_now=False
    )
    modified = models.DateTimeField(
        'modificado em',
        auto_now_add=False,
        auto_now=True
    )

    class Meta:
        abstract = True

projeto/core/views.py
from django.shortcuts import render
from projeto.vendas.models import ItemVenda, Venda
from django.db.models import Sum, F
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from datetime import datetime

def index(request):
    produtos = ItemVenda.objects.values('produto__produto').annotate(total_vendido=Sum('quantidade')).order_by('-total_vendido')

    produtos_nomes = [produto['produto__produto'] for produto in produtos]
    produtos_quantidade = [produto['total_vendido'] for produto in produtos]

    cores = ['#FF5733', '#33FF57', '#3357FF', '#F0FF33', '#FF33A1', '#33FFF7']
    
    produtos_data = [
        {
            'produto': nome,
            'quantidade_vendida': qtd,
            'cor': cores[i % len(cores)]
        }
        for i, (nome, qtd) in enumerate(zip(produtos_nomes, produtos_quantidade))
    ]

    context = {
        'produtos_nomes': produtos_nomes,
        'produtos_quantidade': produtos_quantidade,
        'produtos': produtos_data
    }
    return render(request, 'index.html', context)


def list_vendas(request):
    vendas = Venda.objects.prefetch_related('itens').order_by('-id')

    for venda in vendas:
        venda.total_calculado = sum(
            item.quantidade * item.preco_unitario for item in venda.itens.all()
        )
    
    return render(request, 'list_vendas.html', {'vendas': vendas})


@login_required
def financas(request):
    data_selecionada = request.GET.get('data')
    if data_selecionada:
        try:
            data_selecionada = datetime.strptime(data_selecionada, '%Y-%m-%d').date()
        except ValueError:
            data_selecionada = None
    else:
        data_selecionada = None

    vendas = Venda.objects.all()
    if data_selecionada:
        vendas = vendas.filter(data_venda__date=data_selecionada)

    produtos = ItemVenda.objects.filter(venda__in=vendas).values('produto__produto') \
        .annotate(
            total_vendido=Sum('quantidade'),
            receita_total=Sum(F('quantidade') * F('preco_unitario'))
        ).order_by('-total_vendido')

    valor_total_vendas = sum(produto['receita_total'] for produto in produtos)

    metodos_pagamento = Venda.objects.filter(id__in=vendas).values('forma_pagamento') \
        .annotate(total_vendas=Sum('total')) \
        .order_by('-total_vendas')

    vendas_por_usuario = Venda.objects.filter(id__in=vendas).values('user__nome').annotate(
        total_vendas=Sum('total')
    ).order_by('-total_vendas')

    itens_vendidos = [
        {
            'produto': produto['produto__produto'],
            'quantidade_vendida': produto['total_vendido'],
        }
        for produto in produtos
    ]

    context = {
        'produtos': [
            {
                'produto': produto['produto__produto'],
                'quantidade_vendida': produto['total_vendido'],
                'receita_total': produto['receita_total'],
            }
            for produto in produtos
        ],
        'valor_total_vendas': valor_total_vendas,
        'metodos_pagamento': [
            {
                'metodo': metodo['forma_pagamento'],
                'total_vendas': metodo['total_vendas'],
            }
            for metodo in metodos_pagamento
        ],
        'vendas_por_usuario': vendas_por_usuario,
        'itens_vendidos': itens_vendidos,
    }

    return render(request, 'financa.html', context)


@login_required
def vendas_usuario_detalhes(request, nome):
    vendas = Venda.objects.filter(user__nome=nome).values('forma_pagamento').annotate(
        total_vendido=Sum('total')
    )

    data = [
        {
            'metodo_pagamento': venda['forma_pagamento'],
            'total_vendido': float(venda['total_vendido']),
        }
        for venda in vendas
    ]

    return JsonResponse({'vendas': data})

projeto/core/templates/financa.html
{% extends 'layout.html' %}

{% block conteudo %}
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div class="sidebar" style="background-color: rgb(13, 12, 12);">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link" href="#" onclick="showSection('relatorio-financeiro')">Relatório Financeiro</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#" onclick="showSection('vendas-metodo')">Venda por Método de Pagamento</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#" onclick="showSection('vendas-usuario-metodo')">Venda por Usuário</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#" onclick="showSection('quantidade-itens')">Total de Itens Vendidos</a>
                    </li>
                </ul>
            </div>
        </div>

        <div class="col-md-9" style="justify-content: center; align-items: center; height: 100vh;">
            <div id="selecao-data" class="sidebar col-md-6" style="max-width: 350px; text-align: center; padding: 15px; background-color: rgb(13, 12, 12); left: 25%">
                <form method="get" action="{% url 'core:financas' %}">
                    <div style="display: flex; gap: 10px; justify-content: center;">
                        <div class="form-group">
                            <label for="data_inicial">Data Inicial</label>
                            <input type="date" class="form-control" id="data_inicial" name="data_inicial" value="{{ request.GET.data_inicial }}">
                        </div>
                        <div class="form-group">
                            <label for="data_final">Data Final</label>
                            <input type="date" class="form-control" id="data_final" name="data_final" value="{{ request.GET.data_final }}">
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary mt-2">Filtrar</button>
                </form>
            </div>
            

            <!-- Verificar se o intervalo de datas foi escolhido -->
            {% if request.GET.data_inicial and request.GET.data_final %}
                <!-- Relatório Financeiro -->
            <div id="relatorio-financeiro" class="col-md-12 sidebar content-section" style="background-color: rgb(13, 12, 12);">
                <h2>Relatório Financeiro</h2>
                <hr>
                <h4>Período: {{ request.GET.data_inicial }} a {{ request.GET.data_final }}</h4>
                <hr>
                <h4>Valor Total das Vendas: R$ {{ valor_total_vendas|floatformat:2 }}</h4>
                    <table class="table table-striped">
                        <thead style="color: aliceblue">
                            <tr style="text-align: center;">
                                <th>Produto</th>
                                <th>Quantidade Vendida</th>
                                <th>Receita Total (R$)</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for produto in produtos %}
                            <tr style="text-align: center;">
                                <td style="color: aliceblue">{{ produto.produto }}</td>
                                <td style="color: aliceblue">{{ produto.quantidade_vendida }}</td>
                                <td style="color: aliceblue">R$ {{ produto.receita_total|floatformat:2 }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>

                <!-- Outras seções -->
                <div id="vendas-metodo" class="content-section sidebar" style="background-color: rgb(13, 12, 12);">
                    <h2>Venda por Método de Pagamento</h2>
                    <hr>
                    <table class="table table-striped">
                        <thead style="color: aliceblue">
                            <tr style="text-align: center;">
                                <th>Método de Pagamento</th>
                                <th>Total Vendido (R$)</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for metodo in metodos_pagamento %}
                            <tr style="text-align: center;">
                                <td style="color: aliceblue">{{ metodo.metodo }}</td>
                                <td style="color: aliceblue">R$ {{ metodo.total_vendas|floatformat:2 }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>

                <div id="vendas-usuario-metodo" class="content-section sidebar" style="background-color: rgb(13, 12, 12);">
                    <h2>Vendas por Usuário</h2>
                    <hr>
                    <table class="table table-striped">
                        <thead style="color: aliceblue">
                            <tr style="text-align: center;">
                                <th>Usuário</th>
                                <th>Total Vendido (R$)</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for venda in vendas_por_usuario %}
                            <tr style="text-align: center;">
                                <td>
                                    <a style="color: aliceblue" href="#" onclick="mostrarModal('{{ venda.user__nome }}')">
                                        {{ venda.user__nome }}
                                    </a>
                                </td>
                                <td style="color: aliceblue">R$ {{ venda.total_vendas|floatformat:2 }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>

                <div id="quantidade-itens" class="content-section sidebar" style="background-color: rgb(13, 12, 12);">
                    <h2>Total de Itens Vendidos</h2>
                    <hr>
                    <table class="table table-striped">
                        <thead style="color: aliceblue">
                            <tr style="text-align: center;">
                                <th>Produto</th>
                                <th>Quantidade Vendida</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in itens_vendidos %}
                            <tr style="text-align: center;">
                                <td style="color: aliceblue">{{ item.produto }}</td>
                                <td style="color: aliceblue">{{ item.quantidade_vendida }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% endif %}
        </div>
    </div>
</div>

{% endblock conteudo %}


{% block css %}
<style>
    .sidebar {
        margin-top: 10px;
        border: 1px solid #ddd;
        padding: 20px;
        border-radius: 8px;
        background-color: #f9f9f9;
    }
    .content-section {
        display: none;
    }
    .content-section.active {
        display: block;
    }
    .modal {
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-color: rgba(0, 0, 0, 0.5);
        display: flex;
        justify-content: center;
        align-items: center;
    }
    .modal-content {
        background-color: white;
        padding: 20px;
        border-radius: 8px;
        width: 60%;
        box-shadow: 0 2px 10px rgba(0, 0, 0, 0.2);
    }
    .close {
        float: right;
        cursor: pointer;
        font-size: 20px;
    }
</style>
{% endblock css %}

{% block js %}
<script>
    function showSection(sectionId) {
        document.querySelectorAll('.content-section').forEach(section => section.style.display = 'none');
        document.getElementById(sectionId).style.display = 'block';
    }
    function mostrarModal(username) {
        fetch(`/vendas-usuario-detalhes/${username}/`).then(response => response.json()).then(data => {
            const modalContentBody = document.getElementById('modal-content-body');
            modalContentBody.innerHTML = '';
            data.vendas.forEach(venda => {
                modalContentBody.innerHTML += `<tr><td>${venda.metodo_pagamento}</td><td>R$ ${venda.total_vendido.toFixed(2)}</td></tr>`;
            });
            document.getElementById('modal').style.display = 'flex';
        });
    }
    function fecharModal() {
        document.getElementById('modal').style.display = 'none';
    }
    showSection('relatorio-financeiro');
</script>
{% endblock js %}

projeto/core/templates/index.html
{% extends 'layout.html' %}

{% block conteudo %}
<div class="container">
    <br>
    <br>
    <div class="row">
        <div class="col-md-4 ">
            <h2>Produtos Vendidos</h2>
            <canvas id="produtosChart"></canvas>
        </div>
        <div class="col-md-4">
            <h3>Alertas</h3>
            <div class="alert alert-info" role="alert">
                <strong>Informativo!</strong> Nova venda registrada.
            </div>
        </div>
    </div>
</div>
{% endblock conteudo %}

{% block css %}
<style>
    .sidebar {
        margin-top: 10px;
        border: 1px solid #ddd;
        padding: 20px;
        border-radius: 8px;
        background-color: #f9f9f9;
    }
</style>
{% endblock css %}

{% block js %}
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
    var produtosNomes = {{ produtos_nomes|safe }};
    var produtosQuantidade = {{ produtos_quantidade|safe }};

    var ctx = document.getElementById('produtosChart').getContext('2d');
    var produtosChart = new Chart(ctx, {
        type: 'pie',
        data: {
            labels: produtosNomes, 
            datasets: [{
                label: 'Produtos Vendidos',
                data: produtosQuantidade,  
                backgroundColor: [
                    'rgba(255, 99, 132, 0.2)',
                    'rgba(54, 162, 235, 0.2)',
                    'rgba(255, 206, 86, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(153, 102, 255, 0.2)',
                    'rgba(255, 159, 64, 0.2)'
                ],
                borderColor: [
                    'rgba(255, 99, 132, 1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)',
                    'rgba(255, 159, 64, 1)'
                ],
                borderWidth: 1
            }]
        }
    });
</script>
{% endblock %}

projeto/core/templates/layout.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Estoque</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    {% block css %}
    {% endblock css %}
  </head>
  <body style="background-color: rgb(20, 18, 18);">
    <nav class="navbar navbar-light bg-light" style="background-color: black !important;">
      <div class="container-fluid">
        <a class="navbar-brand" style="color: aliceblue;" href="{% url 'core:index' %}">Home</a>
        <div class="dropdown">
          <a class="navbar-brand dropdown-toggle" href="#" id="estoqueDropdown" style="color: aliceblue;" role="button" data-bs-toggle="dropdown" aria-expanded="true">
            Produtos
          </a>
          <ul class="dropdown-menu" aria-labelledby="estoqueDropdown">
            <li><a class="dropdown-item" href="{% url 'produto:produto_list' %}">Produtos</a></li>
            <li><a class="dropdown-item" href="{% url 'fornecedores:fornecedor' %}">fornecedores</a></li>
          </ul>
        </div>
        <div class="dropdown">
          <a class="navbar-brand dropdown-toggle" id="estoqueDropdown" style="color: aliceblue;" role="button" data-bs-toggle="dropdown" aria-expanded="true">
            Estoque
          </a>
          <ul class="dropdown-menu" aria-labelledby="estoqueDropdown">
            <li><a class="dropdown-item" href="{% url 'estoque:estoque_entrada_list' %}">Entrada</a></li>
            <li><a class="dropdown-item" href="{% url 'estoque:estoque_saida_list' %}">Saída</a></li>
          </ul>
          
        </div>
        <div class="dropdown">
          <a class="navbar-brand dropdown-toggle" href="#" id="estoqueDropdown" style="color: aliceblue;" role="button" data-bs-toggle="dropdown" aria-expanded="true">
            Vendas
          </a>
        <ul class="dropdown-menu" aria-labelledby="vendasDropdown">
          <li><a class="dropdown-item" href="{% url 'core:list_vendas' %}">listagem</a></li>
          <li><a class="dropdown-item" href="{% url 'vendas:register_venda' %}">venda</a></li>
        </ul>
      </div>
      <div class="d-flex">
        {% if user.is_authenticated %}
        <a class="navbar-brand" style="color: aliceblue;" href="{% url 'core:financas' %}">Financeiro</a>
          <a href="{% url 'user:user_dashboard' %}" class="navbar-brand  btn btn-primary"  style="color: aliceblue; margin-right: 5px;">Meu Perfil</a>
          {% else %}
            <a href="{% url 'user:signin' %}" class="navbar-brand" style="color: aliceblue;">Login</a>
          {% endif %}
        </div>
      </div>
    </nav>
    <div class="container" style="color:aliceblue;">

      {% block conteudo %} 
      {% endblock %}
      </div>
      
      <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>

      {% block js %}
      {% endblock js %}


  </body>
</html>

projeto/core/templates/list_vendas.html
{% extends 'layout.html' %}

{% block conteudo %}
{% load static %}

<div class="container sidebar" style="background-color: rgb(13, 12, 12);">
    <h3 style="text-align: center;">Últimas Vendas:</h3>
    <table class="table table-striped" style="text-align: center;">
        <thead style="color: antiquewhite;">
            <tr>
                <th>Data e Hora</th>
                <th>Forma de Pagamento</th>
                <th>Total (R$)</th>
                <th>Funcionario</th>
                {% if user.is_authenticated %}
                    <th>acoes</th>
                {% endif %}
            </tr>
        </thead>
            <tbody>
                {% for venda in vendas %}
                    <tr>
                        <td style="color: antiquewhite;">{{ venda.data_venda|date:"d/m/Y H:i" }}</td>
                        <td style="color: antiquewhite;">{{ venda.forma_pagamento }}</td>
                        <td style="color: antiquewhite;">{{ venda.total_calculado|floatformat:2 }}</td>
                        <td style="color: antiquewhite;">{{ venda.user.nome }}</td>
                        {% if user.is_authenticated %}  
                        <td>
                            <a href="{% url 'vendas:gerar_recibo' venda_id=venda.id %}">
                                <button class="btn btn-primary">Recibo</button>
                            </a>
                        </td>
                        {% endif %}
                    </tr>
                {% endfor %}
        </tbody>
    </table>
</div>

<script src="{% static 'js/index.js' %}" defer></script>
{% endblock %}

{% block css %}
<style>
    .sidebar {
        margin-top: 10px;
        border: 1px solid #ddd;
        padding: 20px;
        border-radius: 8px;
        background-color: #f9f9f9;
    }
</style>
{% endblock css %}