projeto/core/urls.py
from django.urls import path
from projeto.core import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('list_vendas', views.list_vendas, name='list_vendas'),
    path('financas/', views.financas, name='financas'),
    path('vendas-usuario-detalhes/<str:nome>/', views.vendas_usuario_detalhes, name='vendas_usuario_detalhes'),
]

projeto/estoque/urls.py
from django.urls import path
from projeto.estoque import views 

app_name = 'estoque'

urlpatterns = [
    path('', views.estoque_entrada_list, name='estoque_entrada_list'),
    path('saida/', views.estoque_saida_list, name='estoque_saida_list'),
    path('add/', views.estoque_entrada_add, name='estoque_entrada_add'),  
    path('saida/add/', views.estoque_saida_add, name='estoque_saida_add'),  
    path('entrada/<int:pk>/', views.estoque_entrada_detail, name='estoque_entrada_detail'),
    path('saida/<int:pk>/', views.estoque_saida_detail, name='estoque_saida_detail'),
    path('estoque/baixa/', views.dar_baixa_estoque_add, name='dar_baixa_estoque_add'),
    path('estoque/baixa/saida', views.dar_baixa_estoque_saida, name='dar_baixa_estoque_saida'),
]

projeto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('', include('projeto.core.urls')),
    path('produto/', include('projeto.produto.urls')),
    path('estoque/', include('projeto.estoque.urls')),
    path('vendas/', include('projeto.vendas.urls')),
    path('fornecedores/', include('projeto.fornecedores.urls')),
    path('admin/', admin.site.urls),
    path('user/', include('projeto.user.urls')),
    path('ingrediente/', include('projeto.ingrediente.urls')),
]

projeto/user/urls.py
from django.urls import path 
from projeto.user import views

app_name = 'user'

urlpatterns = [
    path('dashboard/', views.user_dashboard, name='user_dashboard'),
    path('signup/', views.signup, name='signup'),
    path('signin/', views.signin, name='signin'),
    path('logout/', views.logout, name='logout'),
]

projeto/vendas/urls.py
from django.urls import path
from projeto.vendas import views

app_name = 'vendas'

urlpatterns = [
    path('register_venda/', views.register_venda, name='register_venda'),
    path('gerar_recibo/<int:venda_id>/', views.gerar_recibo, name='gerar_recibo'), 
]

projeto/user/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models
from django.contrib.auth.hashers import make_password

class UserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError("O email deve ser fornecido")
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        return self.create_user(email, password, **extra_fields)

class User(AbstractBaseUser, PermissionsMixin):
    nome = models.CharField(max_length=25)
    sobrenome = models.CharField(max_length=25)
    email = models.EmailField(max_length=200, unique=True)
    cpf = models.CharField(max_length=11, unique=True)
    password = models.CharField(max_length=128)

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'  
    REQUIRED_FIELDS = ['nome', 'sobrenome', 'cpf']  

    def __str__(self):
        return self.nome

projeto/user/forms.py
from django import forms
from .models import User

class UserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ["nome", "sobrenome", "email", "cpf", "password"]
        widgets = {
            'password': forms.PasswordInput(),
        }

class LoginForm(forms.Form):
    email = forms.CharField(label="Email", max_length=100)
    password = forms.CharField(label="Senha" ,widget=forms.PasswordInput) 

projeto/user/views.py
from django.shortcuts import render, redirect
from projeto.user.models import User
from projeto.estoque.models import Estoque, EstoqueItens
from projeto.vendas.models import Venda
from projeto.user.forms import UserForm, LoginForm
from django.contrib.auth import authenticate, login, logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.db.models import Max, Sum, Count


def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False) 
            user.set_password(form.cleaned_data['password']) 
            user.save()
            return redirect('core:index')
    else:
        form = UserForm()
    return render(request, "cadastro.html", {"form": form})

def signin(request):
    form = LoginForm()
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data["email"]
            password = form.cleaned_data["password"]
            user = authenticate(username=email, password=password)
            if user is not None:
                login(request, user)
                print("usuario logado!", user)
                return redirect('core:index')
            else:
                if user is None:
                    print(f"Autenticação falhou para email={email} e senha={password}")
                return render(request, 'signin.html', {
                    'form': form,
                    'error': 'email ou senha invalidos.'
                })
    else:
        form = LoginForm()
    return render(request, 'signin.html', {'form':form})

def logout(request):
    auth_logout(request)
    print('usuario deslogado!')
    return redirect("core:index")

@login_required
def user_dashboard(request):
    user = request.user  

    movimentacoes_estoque = Estoque.objects.filter(funcionario=user).order_by('-created')
    entradas_count = movimentacoes_estoque.filter(movimento='e').count()
    saidas_count = movimentacoes_estoque.filter(movimento='s').count()
    ultima_movimentacao = movimentacoes_estoque.aggregate(last_date=Max('created'))['last_date']

    vendas = Venda.objects.filter(user=user)

    total_vendido = vendas.aggregate(total=Sum('total'))['total'] or 0

    vendas_por_metodo = vendas.values('forma_pagamento').annotate(
        quantidade=Count('id'),
        total=Sum('total')
    )

    vendas_por_metodo_dict = {
        venda['forma_pagamento']: {
            'quantidade': venda['quantidade'],
            'total': venda['total']
        }
        for venda in vendas_por_metodo
    }

    context = {
        'user': user,
        'movimentacoes_estoque': movimentacoes_estoque,
        'entradas_count': entradas_count,
        'saidas_count': saidas_count,
        'ultima_movimentacao': ultima_movimentacao,
        'vendas': vendas,
        'total_vendido': total_vendido,
        'vendas_por_metodo': vendas_por_metodo_dict,
    }

    return render(request, 'dashboard.html', context)

projeto/user/templates/cadastro.html
{% extends 'layout.html' %}

{% load widget_tweaks %}

{% block conteudo %}
<div class="d-flex justify-content-center align-items-center" style="height: 90vh; background-color: #f8f9fa;">
    <div class="login-container p-4 bg-white rounded shadow-sm" style="width: 400px;">
        <h2 class="text-center mb-4">Cadastro</h2>
        <form method="post" novalidate>
            {% csrf_token %}
            {% for field in form.visible_fields %}
                <div class="form-group{% if field.errors %} has-error {% endif %} mb-3">
                    <label for="{{ field.id_for_label }}" class="form-label">
                        {% if field.field.required %}
                            <span class="required">{{ field.label }} *</span>
                        {% else %}
                            {{ field.label }}
                        {% endif %}
                    </label>
                    {% render_field field class="form-control" %}
                    {% for error in field.errors %}
                        <span class="text-danger small">{{ error }}</span>
                    {% endfor %}
                </div>
            {% endfor %}
            <div class="d-flex justify-content-between mt-4">
                <button class="btn btn-primary w-100 me-2">
                    <i class="bi bi-check-circle"></i> Cadastrar
                </button>
                <a href="{% url 'core:index' %}" class="btn btn-outline-danger w-100 ms-2">
                    <i class="bi bi-x-circle"></i> Cancelar
                </a>
            </div>
        </form>
        <div class="text-center mt-3">
            <p class="small">Ja tenho conta! <a href="{% url 'user:signin' %}">Entrar</a></p>
        </div>
    </div>
</div>
{% endblock conteudo %}

projeto/user/templates/dashboard.html
{% extends 'layout.html' %}

{% block conteudo %}
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div class="sidebar" style="background-color: rgb(13, 12, 12);">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link" href="#" onclick="showSection('inicio')">Perfil</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#" onclick="showSection('estoque')">Estoque</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#" onclick="showSection('vendas')">Vendas</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:logout' %}">Sair</a>
                    </li>
                </ul>
            </div>
        </div>

        <div class="col-md-6" >
            <div id="inicio" class="content-section" >
                <div class="user-info sidebar" style="background-color: rgb(13, 12, 12);">
                    <h3>Informações do Usuário</h3>
                    <hr>
                    <p><strong>Nome:</strong> {{ user.nome }} {{ user.sobrenome }}</p>
                    <p><strong>Email:</strong> {{ user.email }}</p>
                    <p><strong>CPF:</strong> {{ user.cpf }}</p>
                    <p><strong>Último Login:</strong> {{ user.last_login }}</p>
                </div>
            </div>

            <div id="estoque" class="content-section" style="display: none;">
                <div class="stock-movements sidebar" style="background-color: rgb(13, 12, 12);">
                    <h3>Movimentações de Estoque</h3>
                    <hr>
                    {% if movimentacoes_estoque %}
                    {% for movimento in movimentacoes_estoque %}
                    <div class="movement-item">
                        <strong>Nota Fiscal:</strong> {{ movimento.nf_formated }}<br>
                        <strong>Data:</strong> {{ movimento.created }}<br>
                        <strong>Movimentação:</strong> 
                        <br>
                        {% if movimento.movimento == 'e' %}
                            Entrada
                            <a href="{% url 'estoque:estoque_entrada_detail' movimento.pk %}" class="btn btn-info">Ver Detalhes</a>
                        {% else %}
                            Saída
                            <a href="{% url 'estoque:estoque_saida_detail' movimento.pk %}" class="btn btn-info">Ver Detalhes</a>
                        {% endif %}
                        <br>
                    </div>
                    <hr>
                    {% endfor %}
                    {% else %}
                    <p class="alert alert-warning">Nenhuma movimentação encontrada.</p>
                    {% endif %}
                </div>
            </div>

            <div id="vendas" class="content-section sidebar" style="display: none; background-color: rgb(13, 12, 12);">
                <h3>Vendas</h3>
                <hr>
                {% if vendas %}
                {% for venda in vendas %}
                <div class="sale-item">
                    <p><strong>ID Venda:</strong> {{ venda.id }}</p>
                    <p><strong>Data:</strong> {{ venda.data_venda }}</p>
                    <p><strong>Total:</strong> {{ venda.total }}</p>
                    <a href="{% url 'vendas:gerar_recibo' venda.id %}" class="btn btn-info">Ver Detalhes</a>
                </div>
                <hr>
                {% endfor %}
                {% else %}
                <p class="alert alert-warning">Nenhuma venda encontrada.</p>
                {% endif %}
            </div>
        </div>

        <div class="col-md-3">
            <div id="estoque-summary" class="sidebar" style="display: none; background-color: rgb(13, 12, 12);">
                <h4>Resumo de Estoque</h4>
                <hr>
                <p><strong>Entradas:</strong> <span class="badge bg-primary">{{ entradas_count }}</span></p>
                <p><strong>Saídas:</strong> <span class="badge bg-danger">{{ saidas_count }}</span></p>
                <p><strong>Última Movimentação:</strong></p>
                <p>{{ ultima_movimentacao|date:"d/m/Y H:i" }}</p>
            </div>

            <div id="vendas-summary" style="display: none;">
                <div class="sidebar" style="background-color: rgb(13, 12, 12);">
                    <h4>Resumo de Vendas</h4>
                    <hr>
                    <p><strong>Total Vendido:</strong> R$ {{ total_vendido }}</p>
                </div>
                <div class="sidebar" style="margin-top: 15px; background-color: rgb(13, 12, 12);">
                    <h5>Por Método de Pagamento:</h5>
                    <hr>
                    {% for metodo, data in vendas_por_metodo.items %}
                    <p>
                        <strong>{{ metodo }}:</strong> {{ data.quantidade }} vendas -> R$ {{ data.total|floatformat:2 }}
                    </p>
                    {% endfor %}
                </div>
                
            </div>
        </div>
    </div>
</div>
{% endblock conteudo %}

{% block css %}
<style>
    .container {
        margin-top: 20px;
    }
    .sidebar {
        border: 1px solid #ddd;
        padding: 20px;
        border-radius: 8px;
        background-color: #f9f9f9;
    }
    .content-section {
        display: none;
    }
    .content-section.active {
        display: block;
    }
</style>
{% endblock css %}

{% block js %}
<script>
    function showSection(sectionId) {
        document.querySelectorAll('.content-section').forEach(function (section) {
            section.style.display = 'none';
        });
        document.getElementById(sectionId).style.display = 'block';

        const estoqueSummary = document.getElementById('estoque-summary');
        const vendasSummary = document.getElementById('vendas-summary');

        estoqueSummary.style.display = sectionId === 'estoque' ? 'block' : 'none';
        vendasSummary.style.display = sectionId === 'vendas' ? 'block' : 'none';
    }

    showSection('inicio');
</script>
{% endblock js %}

projeto/user/templates/signin.html
{% extends 'layout.html' %}

{% load widget_tweaks %}

{% block conteudo %}
<div class="d-flex justify-content-center align-items-center" style="height: 80vh; background-color: #f8f9fa;">
    <div class="login-container p-4 bg-white rounded shadow-sm" style="width: 400px;">
        <h2 class="text-center mb-4">Login</h2>
        <form method="post" novalidate>
            {% csrf_token %}
            {% for field in form.visible_fields %}
                <div class="form-group{% if field.errors %} has-error {% endif %} mb-3">
                    <label for="{{ field.id_for_label }}" class="form-label">
                        {% if field.field.required %}
                            <span class="required">{{ field.label }} *</span>
                        {% else %}
                            {{ field.label }}
                        {% endif %}
                    </label>
                    {% render_field field class="form-control" %}
                    {% for error in field.errors %}
                        <span class="text-danger small">{{ error }}</span>
                    {% endfor %}
                </div>
            {% endfor %}
            <div class="d-flex justify-content-between mt-4">
                <button type="submit" class="btn btn-primary w-100 me-2">
                    <i class="bi bi-box-arrow-in-right"></i> Entrar
                </button>
            </div>
            <div class="d-flex justify-content-between mt-4">
                <a href="{% url 'core:index' %}" class="btn btn-outline-danger w-100 me-2">
                <i class="bi bi-x-circle"></i> Cancelar
            </a>
            </div>
            <div class="text-center mt-3">
                <p class="small">Não tem uma conta? <a href="{% url 'user:signup' %}">Cadastre-se</a></p>
            </div>
        </form>
    </div>
</div>
{% endblock conteudo %}