projeto/fornecedores/urls.py
from django.urls import path
from projeto.fornecedores import views      

app_name = 'fornecedores'

urlpatterns = [
    path('', views.fornecedor, name='fornecedor'),
    path('add/', views.fornecedor_add, name='fornecedor_add'),
    path('editar/<int:pk>/', views.fornecedor_edit, name='fornecedor_edit'),
    path('delete/<int:pk>/', views.fornecedor_delete, name='fornecedor_delete'),
]

projeto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('', include('projeto.core.urls')),
    path('produto/', include('projeto.produto.urls')),
    path('estoque/', include('projeto.estoque.urls')),
    path('vendas/', include('projeto.vendas.urls')),
    path('fornecedores/', include('projeto.fornecedores.urls')),
    path('admin/', admin.site.urls),
    path('user/', include('projeto.user.urls')),
    path('ingrediente/', include('projeto.ingrediente.urls')),
]

projeto/fornecedores/models.py
from django.db import models

class Fornecedores_loja(models.Model):
    nome = models.CharField(max_length=100, null=False)
    categoria = models.CharField(max_length=100, null=True)


    def __str__(self):
        return self.nome

projeto/fornecedores/forms.py
from django import forms
from .models import Fornecedores_loja

class FornecedorForm(forms.ModelForm):

    class Meta:
        model = Fornecedores_loja
        fields = "__all__"

projeto/fornecedores/views.py
from django.shortcuts import render, redirect, get_object_or_404
from projeto.fornecedores.models import Fornecedores_loja
from projeto.fornecedores.forms import FornecedorForm
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required

@login_required 
def fornecedor(request):
    objects = Fornecedores_loja.objects.all()
    return render(request, "fornecedores_list.html", {"objects": objects})

@login_required 
def fornecedor_add(request):
    if request.method == "POST":
        form = FornecedorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('fornecedores:fornecedor')
    else:
        form = FornecedorForm()
    
    return render(request, "fornecedor_form.html", {"form":form})

@login_required 
def fornecedor_edit(request, pk):
    fornecedor = get_object_or_404(Fornecedores_loja, pk=pk)
    if request.method == "POST":
        form = FornecedorForm(request.POST, instance=fornecedor)
        if form.is_valid():
            form.save()
            return redirect("fornecedores:fornecedor")
    else:
        form = FornecedorForm(instance=fornecedor)
    return render(request, "fornecedor_form.html", {"form": form})

def fornecedor_delete(request, pk):
    fornecedor = get_object_or_404(Fornecedores_loja, pk=pk)
    fornecedor.delete()
    return redirect("fornecedores:fornecedor")

def fornecedores_json(request, pk):
    try:
        fornecedor = Fornecedores_loja.objects.get(pk=pk)
        data = {
            'id': fornecedor.id,
            'nome': fornecedor.nome,
        }
        return JsonResponse({'data': data})
    
    except Fornecedores_loja.DoesNotExist:
        return JsonResponse({'error': 'Fornecedor não encontrado'}, status=404)
    
    except Exception as e:
        return JsonResponse({'error': f'Erro inesperado: {str(e)}'}, status=500)

projeto/fornecedores/templates/fornecedor_form.html
{% extends 'layout.html' %}

{% load widget_tweaks %}

{% block conteudo %}
<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6 sidebar" style="background-color: rgb(13, 12, 12);">
        <h2>Adicionar Fornecedor:</h2>
        <form method="post" novalidate>
            {% csrf_token %}
            {% for field in form.visible_fields %}
                <div class="form-group{% if field.errors %} has-error {% endif %}">
                    <label for="{{ field.id_for_label }}">
                        {% if field.field.required %}
                            <span class="required">{{ field.label }} *</span>
                        {% else %}
                            {{ field.label }}
                        {% endif %}
                    </label>
                    {% render_field field class="form-control" %}
                    {% for error in field.errors %}
                        <span class="text-danger">{{ error }}</span>
                    {% endfor %}
                </div>
            {% endfor %}
            <div class="d-flex justify-content-between mt-4">
                <button type="submit" class="btn btn-primary">
                    {% if editar %}Salvar Alterações{% else %}Cadastrar{% endif %}
                </button>
                <a href="{% url 'fornecedores:fornecedor' %}" class="btn btn-danger">Cancelar</a>
            </div>
        </form>
    </div>
</div>
{% endblock conteudo %}

{% block css %}
<style>
    .sidebar {
        margin-top: 10px;
        border: 1px solid #ddd;
        padding: 20px;
        border-radius: 8px;
        background-color: #f9f9f9;
    }
</style>
{% endblock css %}

projeto/fornecedores/templates/fornecedores_list.html
{% extends 'layout.html' %}

{% block conteudo %}
<div class="container sidebar" style="background-color: rgb(13, 12, 12);">
<h2>Fornecedores</h2>
<a href="{% url 'fornecedores:fornecedor_add' %}" class="btn btn-primary">Adicionar Fornecedor</a>
<br>
<br>

<table class="table" style="text-align: center;">
    <thead style="color: white;">
        <tr>
            <th>ID</th>
            <th>Nome</th>
            <th>Categoria</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        {% for fornecedor in objects %}
        <tr>
            <td style="color: white;">{{ fornecedor.id }}</td>
            <td style="color: white;">{{ fornecedor.nome }}</td>
            <td style="color: white;">{{ fornecedor.categoria }}</td>
            <td>
                <a href="{% url 'fornecedores:fornecedor_edit' fornecedor.id %}" class="btn btn-primary">Editar</a>
                <a href="{% url 'fornecedores:fornecedor_delete' fornecedor.id %}" class="btn btn-danger">Excluir</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>
{% endblock conteudo %}

{% block css %}
<style>
    .sidebar {
        margin-top: 10px;
        border: 1px solid #ddd;
        padding: 20px;
        border-radius: 8px;
        background-color: #f9f9f9;
    }
</style>
{% endblock css %}