projeto/estoque/urls.py
from django.urls import path
from projeto.estoque import views 

app_name = 'estoque'

urlpatterns = [
    path('', views.estoque_entrada_list, name='estoque_entrada_list'),
    path('saida/', views.estoque_saida_list, name='estoque_saida_list'),
    path('add/', views.estoque_entrada_add, name='estoque_entrada_add'),  
    path('saida/add/', views.estoque_saida_add, name='estoque_saida_add'),  
    path('entrada/<int:pk>/', views.estoque_entrada_detail, name='estoque_entrada_detail'),
    path('saida/<int:pk>/', views.estoque_saida_detail, name='estoque_saida_detail'),
    path('estoque/baixa/', views.dar_baixa_estoque_add, name='dar_baixa_estoque_add'),
    path('estoque/baixa/saida', views.dar_baixa_estoque_saida, name='dar_baixa_estoque_saida'),
]

projeto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('', include('projeto.core.urls')),
    path('produto/', include('projeto.produto.urls')),
    path('estoque/', include('projeto.estoque.urls')),
    path('vendas/', include('projeto.vendas.urls')),
    path('fornecedores/', include('projeto.fornecedores.urls')),
    path('admin/', admin.site.urls),
    path('user/', include('projeto.user.urls')),
    path('ingrediente/', include('projeto.ingrediente.urls')),
]

projeto/estoque/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse_lazy
from projeto.core.models import TimeStampedModel
from projeto.produto.models import Produto
from .managers import EstoqueEntradaManager, EstoqueSaidaManager
from django.conf import settings

MOVIMENTO = (
    ('e', 'entrada'),
    ('s', 'saida'),
)

class Estoque(TimeStampedModel):
    funcionario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    nf = models.PositiveBigIntegerField('nota fiscal', null=True, blank=True)
    movimento = models.CharField(max_length=1, choices=MOVIMENTO)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f"{self.created.strftime('%d/%m/%Y')} - {self.funcionario.username}"

    def nf_formated(self):
        return str(self.nf).zfill(3)

class EstoqueItens(models.Model):
    estoque = models.ForeignKey(Estoque, on_delete=models.CASCADE, related_name='estoques')
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    quantidade = models.DecimalField(max_digits=10, decimal_places=2)
    saldo = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)

    class Meta:
        ordering = ('pk',)

    def __str__(self):
        return f'{self.produto.produto} - Quantidade: {self.quantidade} - Saldo: {self.saldo}'

    def atualizar_estoque(self):
        if self.saldo >= self.quantidade:
            self.saldo -= self.quantidade
            self.save()
        else:
            raise ValueError(f"Estoque insuficiente para o produto {self.produto.produto}!")

    def atualizar_estoque_ingredientes(self):
        for ingrediente in self.produto.ingredientes.all():
            produto_ingrediente = self.produto.produtoingrediente_set.get(ingrediente=ingrediente)
            quantidade_necessaria = produto_ingrediente.quantidade * self.quantidade

            if ingrediente.estoque < quantidade_necessaria:
                raise ValueError(f"Estoque insuficiente para o ingrediente {ingrediente.nome}!")
            
            ingrediente.estoque -= quantidade_necessaria
            ingrediente.save()

class EstoqueEntrada(Estoque):
    objects = EstoqueEntradaManager()

    class Meta:
        proxy = True
        verbose_name = 'estoque entrada'
        verbose_name_plural = 'estoque entrada'

    def get_absolute_url(self):
        return reverse_lazy('estoque:estoque_entrada_detail', kwargs={'pk': self.pk})

class EstoqueSaida(Estoque):
    objects = EstoqueSaidaManager()

    class Meta:
        proxy = True
        verbose_name = 'estoque saída'
        verbose_name_plural = 'estoque saída'

    def get_absolute_url(self):
        return reverse_lazy('estoque:estoque_saida_detail', kwargs={'pk': self.pk})

projeto/estoque/forms.py
from django import forms
from .models import Estoque, EstoqueItens

class EstoqueForm(forms.ModelForm):

    class Meta:
        model = Estoque
        fields = ('nf', 'movimento')
        widgets = {
            'movimento': forms.HiddenInput()
        }
        
class EstoqueItensForm(forms.ModelForm):

    class Meta:
        model = EstoqueItens
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields.pop('saldo')

projeto/estoque/views.py
import json
from django.forms import inlineformset_factory
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from .forms import EstoqueForm, EstoqueItensForm
from .models import Estoque, EstoqueItens, EstoqueEntrada, EstoqueSaida
from projeto.produto.models import Produto
from django.http import JsonResponse

User = get_user_model()

@login_required 
def estoque_entrada_list(request):
    template_name = 'estoque_entrada_list.html'
    objects = EstoqueEntrada.objects.filter(movimento='e')
    context = {'object_list': objects}
    return render(request, template_name, context)

@login_required 
def estoque_entrada_detail(request, pk):
    template_name = 'estoque_entrada_detail.html'
    object = EstoqueEntrada.objects.get(pk=pk)
    if object != None:
        context = {'object': object}
        return render(request, template_name, context)
    return redirect("core:index")

def dar_baixa_estoque_add(estoque):
    produtos = estoque.estoques.all()
    if produtos.exists():
        for item in produtos:
            produto = Produto.objects.get(pk=item.produto.pk)
            produto.estoque += item.quantidade
            produto.save()
            print('estoque atualizado!')
    else:
        print("Nenhum produto encontrado para o estoque.")

def dar_baixa_estoque_saida(estoque):
    produtos = estoque.estoques.all()
    if produtos.exists():
        for item in produtos:
            produto = Produto.objects.get(pk=item.produto.pk)
            produto.estoque -= item.quantidade
            produto.save()
            print('estoque atualizado!')
    else:
        print("Nenhum produto encontrado para o estoque.")

@login_required
def estoque_entrada_add(request):
    if not request.user.is_authenticated:
        return redirect('login') 

    estoque_form = EstoqueEntrada()
    print("Funcionário:", request.user)
    item_estoque_formset = inlineformset_factory(
        EstoqueEntrada,
        EstoqueItens,
        form=EstoqueItensForm,
        extra=0,
        min_num=0,
        validate_min=True,
        can_delete=False,
    )

    if request.method == 'POST':
        form = EstoqueForm(request.POST, instance=estoque_form)
        formset = item_estoque_formset(request.POST, instance=estoque_form)

        if form.is_valid() and formset.is_valid():
            estoque = form.save(commit=False)
            estoque.funcionario = request.user
            estoque.movimento = 'e'
            estoque.save()
            formset.instance = estoque
            formset.save()
            dar_baixa_estoque_add(estoque)
            return redirect('estoque:estoque_entrada_detail', pk=estoque.pk)
    else:
        form = EstoqueForm(instance=estoque_form)
        form.fields['movimento'].initial = 'e'
        formset = item_estoque_formset(instance=estoque_form)

    return render(request, 'estoque_entrada_form.html', {
        'form': form,
        'formset': formset,
    })

@login_required 
def estoque_saida_list(request):
    template_name = 'estoque_saida_list.html'
    objects = EstoqueSaida.objects.filter(movimento='s')
    context = {'object_list': objects}
    return render(request, template_name, context)

@login_required
def estoque_saida_add(request):
    estoque_form = Estoque()
    item_estoque_formset = inlineformset_factory(
        Estoque,
        EstoqueItens,
        form=EstoqueItensForm,
        extra=0,
        min_num=0,
        validate_min=True,
        can_delete=False,
    )

    if request.method == 'POST':
        form = EstoqueForm(request.POST, instance=estoque_form)
        formset = item_estoque_formset(request.POST, instance=estoque_form)

        if form.is_valid() and formset.is_valid():
            estoque = form.save(commit=False)
            estoque.funcionario = request.user
            estoque.movimento = 's'
            estoque.save()
            formset.instance = estoque
            formset.save()
            dar_baixa_estoque_saida(estoque)
            return redirect('estoque:estoque_saida_detail', pk=estoque.pk)

    else:
        form = EstoqueForm(instance=estoque_form)
        form.fields['movimento'].initial = 's'
        formset = item_estoque_formset(instance=estoque_form)

    return render(request, 'estoque_saida_form.html', {
        'form': form,
        'formset': formset,
    })

@login_required 
def estoque_saida_detail(request, pk):
    template_name = 'estoque_saida_detail.html'
    object = EstoqueSaida.objects.get(pk=pk)
    if object != None:
        context = {'object': object}
        return render(request, template_name, context)
    return redirect("core:index")

projeto/estoque/templates/estoque_entrada_detail.html
{% extends 'layout.html' %}

{% block conteudo %}

<div class="container sidebar" style="margin-top: 5px; background-color: rgb(13, 12, 12);">
    <div class="container">
      <a href="{% url 'estoque:estoque_entrada_list' %}">
        <button type="button" class="btn btn-primary">
          Voltar
        </button>
      </a>
      <h2 style="text-align: center;">{{ object }}</h2>
      <br>
      <div class="col-md-6 mx-auto">
        <table class="table table-user-information">
            <tbody style="color: white;">
                <tr>
                    <th class="text-right">Nota Fiscal</th>
                    <td>{{ object.nf_formated }}</td>
                </tr>
                <tr>
                    <th class="text-right">Data</th>
                    <td>{{ object.created }}</td>
                </tr>
                <tr>
                    <th class="text-right">Funcionario</th>
                    <td>{{ object.funcionario }}</td>
                </tr>
            </tbody>
        </table>
      </div>
    </div>
    <div class="table-responsive col-md-6  mx-auto" style="text-align: center;">
        <table class="table table-striped">
            <legend>Produtos:</legend>
            <thead style="color: white;">
                <tr>
                    <th>Produto</th>
                    <th>Quantidade</th>
                </tr>
            </thead>
            <tbody>
                {% for object in object.estoques.all %}
                <tr>
                    <td style="color: white;">{{ object.produto }}</td>
                    <td style="color: white;">{{ object.quantidade }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
      </div>

</div>

{% endblock conteudo %}

{% block css %}
<style>
    .sidebar {
        margin-top: 10px;
        border: 1px solid #ddd;
        padding: 20px;
        border-radius: 8px;
        background-color: #f9f9f9;
    }
</style>
{% endblock css %}

projeto/estoque/templates/estoque_entrada_form.html
{% extends 'layout.html' %}
{% load widget_tweaks %}
{% load bootstrap %}

{% block conteudo %}
<div class="container sidebar" style="background-color: rgb(13, 12, 12);">
    <div id="error-message" class="alert alert-danger" style="display: none;">
        <strong>Erro:</strong> Não foi possível adicionar o item. Verifique os campos.
    </div>

    <form method="POST" novalidate>
        {% csrf_token %}
        <legend>Entrada do Estoque</legend>

        <div>
            {% for field in form.visible_fields %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {% render_field field class="form-control" %}
                </div>
            {% endfor %}

            <input type="hidden" name="movimento" value="e">

            {{ formset.management_form }}
        </div>

        <div class="row">
            <div class="col-sm-6">
                <legend style="border-bottom: 1px solid #e5e5e5;">Produtos</legend>
                <div id="estoque" class="form-inline">
                    {% for item_estoque_form in formset %}
                    <div id="item-{{ forloop.counter0 }}" class="form-group">
                        {% for field in item_estoque_form %}
                        <div class="form-group">
                            <label for="{{ field.id_for_label }}">{{ field.label|cut:"Estoque" }}</label>
                            {% render_field field class="form-control" %}
                        </div>
                        {% endfor %}
                    </div>
                    {% endfor %}
                </div>
                <span id="add-item" class="btn btn-info" style="margin-top: 10px;">
                    <i class="fa fa-plus"></i> Adicionar
                </span>
            </div>
        </div>

        <div style="margin-top: 10px;">
            <button type="submit" class="btn btn-primary">Salvar</button>
            <a href="{% url 'estoque:estoque_entrada_list' %}" class="btn btn-danger">Cancelar</a>
        </div>
    </form>
</div>
{% endblock conteudo %}

{% block css %}
<style>
    .form-control {
        margin: 10px;
    }
    .sidebar {
        margin-top: 10px;
        border: 1px solid #ddd;
        padding: 20px;
        border-radius: 8px;
        background-color: #f9f9f9;
    }
</style>
{% endblock css %}

{% block js %}
<script>
    let estoques = {}; 

    function addClassesToFields() {
        $('input[id*="-produto"]').addClass('clProduto');
        $('input[id*="-quantidade"]').addClass('clquantidade');
        $('input[id*="-saldo"]').addClass('clSaldo');
    }

    $(document).ready(function () {
        addClassesToFields();

        $('#add-item').click(function (ev) {
            ev.preventDefault();
            let totalFormsInput = $('#id_estoques-TOTAL_FORMS');  
            let totalForms = parseInt(totalFormsInput.val());
            let newFormIndex = totalForms; 
            let tmplMarkup = $('#item-estoque').html();
            let compiledTmpl = tmplMarkup.replace(/__prefix__/g, newFormIndex);

            $('#estoque').append(compiledTmpl);

            totalFormsInput.val(newFormIndex + 1);

            let newForm = $('#item-' + newFormIndex);
            newForm.find('input, select, textarea').each(function () {
                let name = $(this).attr('name');
                if (name) {
                    $(this).attr('name', name.replace(/__prefix__/, newFormIndex));
                }
                let id = $(this).attr('id');
                if (id) {
                    $(this).attr('id', id.replace(/__prefix__/, newFormIndex));
                }

                if (name.includes('produto')) {
                    $(this).addClass('clProduto');
                } else if (name.includes('quantidade')) {
                    $(this).addClass('clquantidade');
                } else if (name.includes('saldo')) {
                    $(this).addClass('clSaldo');
                }
            });
        });
    });

    $(document).on('change', '.clProduto', function() {
        let self = $(this);
        let pk = self.val();
        let url = '/produto/' + pk + '/json/';

        $.ajax({
            url: url,
            type: 'GET',
            success: function(response) {
                let estoque = response.data[0].estoque;  
                let campoQuantidade = self.attr('id').replace('produto', 'quantidade');
                let campoSaldo = self.attr('id').replace('produto', 'saldo');

                estoques[pk] = estoque;

                $('#' + campoSaldo).val(estoque);  
                $('#' + campoQuantidade).val(''); 
            },
            error: function(xhr) {
                console.error('Erro ao buscar os dados do produto:', xhr);
            }
        });
    });

    $(document).on('change', '.clquantidade', function(event) {
    let self = $(this);
    let quantidade = Number(self.val()) || 0;
    let campoProduto = self.attr('id').replace('quantidade', 'produto');
    let pk = $('#' + campoProduto).val();

    if (pk) {
        let campoSaldo = self.attr('id').replace('quantidade', 'saldo');
        let estoque = estoques[pk];  

        if (estoque !== undefined) {
            let novoSaldo = estoque + quantidade;
            $('#' + campoSaldo).val(novoSaldo); 
        }
    } else {
        alert('Selecione um produto antes de inserir quantidade');
    }
});
</script>

<script type="text/html" id="item-estoque">
    <div id="item-__prefix__" class="form-group" style="margin-top: 10px;">
        {{ formset.empty_form|bootstrap }}
    </div>
</script>
{% endblock js %}

projeto/estoque/templates/estoque_entrada_list.html
{% extends 'layout.html' %}

{% block conteudo %}
<div class="container sidebar" style="background-color: rgb(13, 12, 12);">
    <h2>Entrada no Estoque:
    <span class="pull-right">
        <a href="{% url 'estoque:estoque_entrada_add' %}">
            <button type="button" class="btn btn-primary">
                <span class="fa fa-plus"></span>Adicionar
            </button>
        </a>
    </span>
    </h2>

    {% if object_list %}
    <table class="table table-striped">
        <thead style="color: white;">
            <tr  style="text-align: center;">
                <th>Nf</th>
                <th>Data</th>
                <th>Funcionario</th>
            </tr>
        </thead>
        <tbody>
            {% for object in object_list %}
            <tr style="text-align: center;">
                <td style="color: white;"><a href="{% url 'estoque:estoque_entrada_detail' object.id %}">{{ object.nf_formated }}</a></td>
                <td style="color: white;">{{ object.created }}</td>
                <td style="color: white;">{{ object.funcionario }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p class="alert alert-warning">Sem itens na lista</p>
    {% endif %}
</div>
{% endblock conteudo %}

{% block css %}
<style>
    .sidebar {
        margin-top: 10px;
        border: 1px solid #ddd;
        padding: 20px;
        border-radius: 8px;
        background-color: #f9f9f9;
    }
</style>
{% endblock css %}

projeto/estoque/templates/estoque_saida_detail.html
{% extends 'layout.html' %}

{% block conteudo %}

<div class="container sidebar" style="margin-top: 5px; background-color: rgb(13, 12, 12);">
    <div class="container">
      <a href="{% url 'estoque:estoque_entrada_list' %}">
        <button type="button" class="btn btn-primary">
          Voltar
        </button>
      </a>
      <h2 style="text-align: center;">{{ object }}</h2>
      <br>
      <div class="col-sm-6 mx-auto">
        <table class="table table-user-information" style="color: white;">
            <tbody>
                <tr>
                    <th class="text-right">Nota Fiscal</th>
                    <td>{{ object.nf_formated }}</td>
                </tr>
                <tr>
                    <th class="text-right">Data</th>
                    <td>{{ object.created }}</td>
                </tr>
                <tr>
                    <th class="text-right">Funcionario</th>
                    <td>{{ object.funcionario }}</td>
                </tr>
            </tbody>
        </table>
      </div>
    </div>
    <div class="table-responsive col-md-6 mx-auto" style="text-align: center;">
        <table class="table table-striped">
            <legend>Produtos:</legend>
            <thead style="color: white;">
                <tr>
                    <th>Produto</th>
                    <th>Quantidade</th>
                </tr>
            </thead>
            <tbody>
                {% for object in object.estoques.all %}
                <tr>
                    <td style="color: white;">{{ object.produto }}</td>
                    <td style="color: white;">{{ object.quantidade }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
      </div>

</div>

{% endblock %}

{% block css %}
<style>
    .sidebar {
        margin-top: 10px;
        border: 1px solid #ddd;
        padding: 20px;
        border-radius: 8px;
        background-color: #f9f9f9;
    }
</style>
{% endblock css %}

projeto/estoque/templates/estoque_saida_form.html
{% extends 'layout.html' %}
{% load widget_tweaks %}
{% load bootstrap %}

{% block conteudo %}
<div class="container sidebar" style="background-color: rgb(13, 12, 12);">
    <div id="error-message" class="alert alert-danger" style="display: none;">
        <strong>Erro:</strong> Não foi possível adicionar o item. Verifique os campos.
    </div>

    <form method="POST" novalidate>
        {% csrf_token %}
        <legend>Estoque Saída</legend>

        <div>
            {% for field in form.visible_fields %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {% render_field field class="form-control" %}
                </div>
            {% endfor %}
            
            <input type="hidden" name="movimento" value="s">

            {{ formset.management_form }}
        </div>

        <div class="row">
            <div class="col-sm-6">
                <legend style="border-bottom: 1px solid #e5e5e5;">Produtos</legend>
                <div id="estoque" class="form-inline">
                    {% for item_estoque_form in formset %}
                    <div id="item-{{ forloop.counter0 }}" class="form-group">
                        {% for field in item_estoque_form %}
                        <div class="form-group">
                            <label for="{{ field.id_for_label }}">{{ field.label|cut:"Estoque" }}</label>
                            {% render_field field class="form-control" %}
                        </div>
                        {% endfor %}
                    </div>
                    {% endfor %}
                    
                </div>
                <span id="add-item" class="btn btn-info" style="margin-top: 10px;">
                    <i class="fa fa-plus"></i> Adicionar
                </span>
            </div>
        </div>

        <div style="margin-top: 10px;">
            <button type="submit" class="btn btn-primary">Salvar</button>
            <a href="{% url 'estoque:estoque_saida_list' %}" class="btn btn-danger">Cancelar</a>
        </div>
    </form>
</div>
{% endblock conteudo %}

{% block css %}
<style>
    .form-control {
        margin: 10px;
    }
    .sidebar {
        margin-top: 10px;
        border: 1px solid #ddd;
        padding: 20px;
        border-radius: 8px;
        background-color: #f9f9f9;
    }
</style>
{% endblock css %}


{% block js %}
<script>
    let estoques = {}; 

    function addClassesToFields() {
        $('input[id*="-produto"]').addClass('clProduto');
        $('input[id*="-quantidade"]').addClass('clquantidade');
        $('input[id*="-saldo"]').addClass('clSaldo');
    }

    $(document).ready(function () {
        addClassesToFields();

        $('#add-item').click(function (ev) {
            ev.preventDefault();
            let totalFormsInput = $('#id_estoques-TOTAL_FORMS');  
            let totalForms = parseInt(totalFormsInput.val());
            let newFormIndex = totalForms; 
            let tmplMarkup = $('#item-estoque').html();
            let compiledTmpl = tmplMarkup.replace(/__prefix__/g, newFormIndex);

            $('#estoque').append(compiledTmpl);

            totalFormsInput.val(newFormIndex + 1);

            let newForm = $('#item-' + newFormIndex);
            newForm.find('input, select, textarea').each(function () {
                let name = $(this).attr('name');
                if (name) {
                    $(this).attr('name', name.replace(/__prefix__/, newFormIndex));
                }
                let id = $(this).attr('id');
                if (id) {
                    $(this).attr('id', id.replace(/__prefix__/, newFormIndex));
                }

                if (name.includes('produto')) {
                    $(this).addClass('clProduto');
                } else if (name.includes('quantidade')) {
                    $(this).addClass('clquantidade');
                } else if (name.includes('saldo')) {
                    $(this).addClass('clSaldo');
                }
            });
        });
    });

    $(document).on('change', '.clProduto', function() {
        let self = $(this);
        let pk = self.val();
        let url = '/produto/' + pk + '/json/';

        $.ajax({
            url: url,
            type: 'GET',
            success: function(response) {
                let estoque = response.data[0].estoque;  
                let campoQuantidade = self.attr('id').replace('produto', 'quantidade');
                let campoSaldo = self.attr('id').replace('produto', 'saldo');

                estoques[pk] = estoque;

                $('#' + campoSaldo).val(estoque);  
                $('#' + campoQuantidade).val(''); 
            },
            error: function(xhr) {
                console.error('Erro ao buscar os dados do produto:', xhr);
            }
        });
    });

    $(document).on('change', '.clquantidade', function(event) {
        let self = $(this);
        let quantidade = Number(self.val()) || 0;
        let campoProduto = self.attr('id').replace('quantidade', 'produto');
        let pk = $('#' + campoProduto).val();

        if (pk) {
            let campoSaldo = self.attr('id').replace('quantidade', 'saldo');
            let estoque = estoques[pk];  

            if (estoque !== undefined) {
                let novoSaldo = estoque - quantidade;
                $('#' + campoSaldo).val(novoSaldo);  
            }
        } else {
            alert('Selecione um produto antes de inserir quantidade');
        }
    });
</script>

<script type="text/html" id="item-estoque">
    <div id="item-__prefix__" class="form-group" style="margin-top: 10px;">
        {{ formset.empty_form|bootstrap }}
    </div>
</script>
{% endblock js %}

projeto/estoque/templates/estoque_saida_list.html
{% extends 'layout.html' %}

{% block conteudo %}
<div class="container sidebar" style="background-color: rgb(13, 12, 12);">
    <h2>Saida do Estoque:
    <span class="pull-right">
        <a href="{% url 'estoque:estoque_saida_add' %}">
            <button type="button" class="btn btn-primary">
                <span class="fa fa-plus"></span>Adicionar
            </button>
        </a>
    </span>
    </h2>

    {% if object_list %}
    <table class="table table-striped">
        <thead style="text-align: center; color: white;">
            <tr>
                <th>Nf</th>
                <th>Data</th>
                <th>Funcionario</th>
            </tr>
        </thead>
        <tbody style="text-align: center;">
            {% for object in object_list %}
            <tr>
                <td style="color: white;"><a href="{% url 'estoque:estoque_saida_detail' object.id %}">{{ object.nf_formated }}</a></td>
                <td style="color: white;">{{ object.created }}</td>
                <td style="color: white;">{{ object.funcionario }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p class="alert alert-warning">Sem itens na lista</p>
    {% endif %}
</div>
{% endblock conteudo %}

{% block css %}
<style>
    .sidebar {
        margin-top: 10px;
        border: 1px solid #ddd;
        padding: 20px;
        border-radius: 8px;
        background-color: #f9f9f9;
    }
</style>
{% endblock css %}